# Generated by Django 2.2.6 on 2019-11-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='distributor/images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Distribuidora',
                'verbose_name_plural': 'Distribuidoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Atalho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images', verbose_name='Imagem')),
                ('category', models.CharField(choices=[('Sem categoria', 'Sem Categoria'), ('Bebidas', 'Bebidas'), ('Alimentos', 'Alimentos'), ('Higiene', 'Higiene'), ('Roupas', 'Roupas'), ('Eletrodomésticos', 'Eletrodomestico')], default='sem categoria', max_length=100, verbose_name='Categorias')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to='products.Distributor', verbose_name='Distribuidora')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
